name: build CI
on: [push,workflow_call]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get the repository
              uses: actions/checkout@v5
            - name: install dependencies
              uses: actions/setup-node@v4
              with: 
                node-version: 18
            - name: Install npm
              working-directory: ".github/workflows/code/ Basics/02 Starting Project"
              run: npm install
            - name: Run tests
              working-directory: ".github/workflows/code/02 Basics/02 Starting Project"
              run: npm test


